classification: computer
color: ''
description_extra: ''
description_main: 100_mm_width_100_mm_height
id: computer_monitor_mount_vesa_100_mm_width_100_mm_height
manufacturer: ''
part_number: ''
size: vesa
type: monitor_mount
