classification: computer
color: ''
description_extra: ''
description_main: 1920_pixel_width_1080_pixel_height
id: computer_monitor_558_8_mm_screen_diagonal_1920_pixel_width_1080_pixel_height_dell_e2211hb
manufacturer: dell
part_number: e2211hb
size: 558_8_mm_screen_diagonal
type: monitor
