classification: computer
color: ''
description_extra: ''
description_main: ''
id: computer_docking_station_microsoft_surface_microsoft_1661
manufacturer: microsoft
part_number: '1661'
size: microsoft_surface
type: docking_station
