classification: computer
color: ''
description_extra: ''
description_main: pro_4
id: computer_tablet_microsoft_surface_pro_4_microsoft_model_1724
manufacturer: microsoft
part_number: model_1724
size: microsoft_surface
type: tablet
