classification: computer
color: ''
description_extra: ''
description_main: ''
id: computer_webcam_external_microsoft_hd_3000_model_1492
manufacturer: microsoft
part_number: hd_3000_model_1492
size: external
type: webcam
