classification: computer
color: ''
description_extra: ''
description_main: pro_5
id: computer_tablet_microsoft_surface_pro_5_microsoft_model_1796
manufacturer: microsoft
part_number: model_1796
size: microsoft_surface
type: tablet
