classification: computer
color: ''
description_extra: ''
description_main: pro_3
id: computer_tablet_microsoft_surface_pro_3_microsoft_model_1631
manufacturer: microsoft
part_number: model_1631
size: microsoft_surface
type: tablet
