classification: computer
color: ''
description_extra: ''
description_main: docking_station
id: computer_power_supply_microsoft_surface_docking_station_microsoft_model_1749
manufacturer: microsoft
part_number: model_1749
size: microsoft_surface
type: power_supply
