classification: computer
color: ''
description_extra: ''
description_main: max_11
id: computer_tablet_amazon_fire_max_11_amazon_kfsnwi
manufacturer: amazon
part_number: kfsnwi
size: amazon_fire
type: tablet
