classification: computer
color: ''
description_extra: ''
description_main: standalone
id: computer_power_supply_microsoft_surface_standalone_microsoft_model_1625
manufacturer: microsoft
part_number: model_1625
size: microsoft_surface
type: power_supply
