classification: computer
color: ''
description_extra: ''
description_main: 1680_pixel_width_1050_pixel_height
id: computer_monitor_508_mm_screen_diagonal_1680_pixel_width_1050_pixel_height_dell_e2009wt
manufacturer: dell
part_number: e2009wt
size: 508_mm_screen_diagonal
type: monitor
