classification: computer
color: ''
description_extra: ''
description_main: pro_7
id: computer_tablet_microsoft_surface_pro_7_microsoft_model_1866
manufacturer: microsoft
part_number: model_1866
size: microsoft_surface
type: tablet
